### ISSUE TITLE
xpra, xpra2 and xvfb not showing window

### ISSUE THREAD

**Issue by kumikooumae** [mviereck/x11docker#462]
X server options xpra, xpra2 and xvfb does not pop up a window for me. And I installed xpra on host and add --xc=no, it didn't work either. However I can start the container with printenv, start xpra server on host with env, connect xpra client on host to the server, and see the window.
[x11docker.log](https://github.com/mviereck/x11docker/files/9248940/x11docker.log)

**Comment by mviereck** [comment]
Thank you for the report!
I have fixed the issue and have made a new release 7.4.1 including the fix. There was a bug checking the progress of xinitrc preventing xpra to start.
You can install it with `x11docker --update` in a few minutes.

**Comment by kumikooumae** [comment]
Still getting error for `--xpra` at 7.4.1. `--xpra --xc=no` and `--xpra2` works for me now.

error: list of process IDs must follow -p

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text.

For more details see ps(1).
12792 frames in 5.0 seconds = 2558.346 FPS
x11docker note: Option --xpra: xpra terminated unexpectedly.
  Last lines of xpra server log:  257217 ?        00:00:00 xpra
x11docker [01:57:56,862]: Starting Xpra server
db3d50840f57626e04047c3469994dd3ac881cd9266ec8582435052837b6e33c
---------------------------------
  Last lines of xpra client log: 
x11docker [01:57:57,105]: Starting Xpra client
9c8ed0d8b8b723023ab1983b7ac1834debc9827ef6e3e04225108fe3b8941b36

X connection to :101 broken (explicit kill or server shutdown).
[x11docker.log](https://github.com/mviereck/x11docker/files/9257441/x11docker.log)

**Comment by mviereck** [comment]
Thank you for your thorough testing!
I have fixed this in the master/beta version

The issue was that x11docker wants the xpra client to use Wayland if available, but was not set up correctly (environment variable `GDK_BACKEND=wayland` was needed). Your desktop provides Wayland and X11/Xwayland, Gnome 3, I assume.

**Comment by kumikooumae** [comment]
Thanks, it works
